const STUDIO_DATA = [
  {
    "Year": 2015,
    "Company": "ITV Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1232.0,
    "Operating Profit (Local)": 206.0,
    "Operating Margin (%)": 16.72,
    "Exchange Rate (to EUR)": 1.378,
    "Total Revenue (EUR)": 1697.7,
    "Operating Profit (EUR)": 283.87,
    "Work-for-Hire (EUR)": 984.66,
    "Owned IP (EUR)": 169.77,
    "Catalog & Format (EUR)": 543.26,
    "M&A Remark": "Talpa Mediaを3億5500万ポンドで買収。これより『The Voice』等の世界的ノンスクリプテッド・フォーマット権の保有を強化。",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2016,
    "Company": "ITV Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1475.0,
    "Operating Profit (Local)": 243.0,
    "Operating Margin (%)": 16.47,
    "Exchange Rate (to EUR)": 1.2248,
    "Total Revenue (EUR)": 1806.58,
    "Operating Profit (EUR)": 297.63,
    "Work-for-Hire (EUR)": 993.62,
    "Owned IP (EUR)": 216.79,
    "Catalog & Format (EUR)": 596.17,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2017,
    "Company": "ITV Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1607.0,
    "Operating Profit (Local)": 243.0,
    "Operating Margin (%)": 15.12,
    "Exchange Rate (to EUR)": 1.1413,
    "Total Revenue (EUR)": 1834.07,
    "Operating Profit (EUR)": 277.34,
    "Work-for-Hire (EUR)": 972.06,
    "Owned IP (EUR)": 275.11,
    "Catalog & Format (EUR)": 586.9,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2018,
    "Company": "ITV Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1778.0,
    "Operating Profit (Local)": 250.0,
    "Operating Margin (%)": 14.06,
    "Exchange Rate (to EUR)": 1.1301,
    "Total Revenue (EUR)": 2009.32,
    "Operating Profit (EUR)": 282.53,
    "Work-for-Hire (EUR)": 1024.75,
    "Owned IP (EUR)": 361.68,
    "Catalog & Format (EUR)": 622.89,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2019,
    "Company": "ITV Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1821.0,
    "Operating Profit (Local)": 267.0,
    "Operating Margin (%)": 14.66,
    "Exchange Rate (to EUR)": 1.1397,
    "Total Revenue (EUR)": 2075.39,
    "Operating Profit (EUR)": 304.3,
    "Work-for-Hire (EUR)": 1016.94,
    "Owned IP (EUR)": 415.08,
    "Catalog & Format (EUR)": 643.37,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2020,
    "Company": "ITV Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1601.0,
    "Operating Profit (Local)": 137.0,
    "Operating Margin (%)": 8.56,
    "Exchange Rate (to EUR)": 1.1246,
    "Total Revenue (EUR)": 1800.48,
    "Operating Profit (EUR)": 154.07,
    "Work-for-Hire (EUR)": 900.24,
    "Owned IP (EUR)": 288.08,
    "Catalog & Format (EUR)": 612.16,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2021,
    "Company": "ITV Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1775.0,
    "Operating Profit (Local)": 210.0,
    "Operating Margin (%)": 11.83,
    "Exchange Rate (to EUR)": 1.163,
    "Total Revenue (EUR)": 2064.33,
    "Operating Profit (EUR)": 244.23,
    "Work-for-Hire (EUR)": 990.88,
    "Owned IP (EUR)": 392.22,
    "Catalog & Format (EUR)": 681.23,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2022,
    "Company": "ITV Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 2058.0,
    "Operating Profit (Local)": 259.0,
    "Operating Margin (%)": 12.59,
    "Exchange Rate (to EUR)": 1.1733,
    "Total Revenue (EUR)": 2414.65,
    "Operating Profit (EUR)": 303.88,
    "Work-for-Hire (EUR)": 1134.89,
    "Owned IP (EUR)": 507.08,
    "Catalog & Format (EUR)": 772.69,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2023,
    "Company": "ITV Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 2170.0,
    "Operating Profit (Local)": 286.0,
    "Operating Margin (%)": 13.18,
    "Exchange Rate (to EUR)": 1.1492,
    "Total Revenue (EUR)": 2493.76,
    "Operating Profit (EUR)": 328.67,
    "Work-for-Hire (EUR)": 1246.88,
    "Owned IP (EUR)": 423.94,
    "Catalog & Format (EUR)": 822.94,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2024,
    "Company": "ITV Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 2038.0,
    "Operating Profit (Local)": 299.0,
    "Operating Margin (%)": 14.67,
    "Exchange Rate (to EUR)": 1.1809,
    "Total Revenue (EUR)": 2406.67,
    "Operating Profit (EUR)": 353.09,
    "Work-for-Hire (EUR)": 1251.47,
    "Owned IP (EUR)": 312.87,
    "Catalog & Format (EUR)": 842.34,
    "M&A Remark": "EBITA営業利益に、英国の新しい映像制作税制優遇措置（AVEC）による1300万ポンドの還付メリットが含まれる。",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2025,
    "Company": "ITV Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 2130.0,
    "Operating Profit (Local)": 297.0,
    "Operating Margin (%)": 13.94,
    "Exchange Rate (to EUR)": 1.1669,
    "Total Revenue (EUR)": 2485.5,
    "Operating Profit (EUR)": 346.57,
    "Work-for-Hire (EUR)": 1317.31,
    "Owned IP (EUR)": 273.4,
    "Catalog & Format (EUR)": 894.78,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2015,
    "Company": "Fremantle",
    "Currency": "EUR",
    "Total Revenue (Local)": 1472.0,
    "Operating Profit (Local)": 105.0,
    "Operating Margin (%)": 7.13,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 1472.0,
    "Operating Profit (EUR)": 105.0,
    "Work-for-Hire (EUR)": 839.04,
    "Owned IP (EUR)": 220.8,
    "Catalog & Format (EUR)": 412.16,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2016,
    "Company": "Fremantle",
    "Currency": "EUR",
    "Total Revenue (Local)": 1500.0,
    "Operating Profit (Local)": 110.0,
    "Operating Margin (%)": 7.33,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 1500.0,
    "Operating Profit (EUR)": 110.0,
    "Work-for-Hire (EUR)": 810.0,
    "Owned IP (EUR)": 270.0,
    "Catalog & Format (EUR)": 420.0,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2017,
    "Company": "Fremantle",
    "Currency": "EUR",
    "Total Revenue (Local)": 1472.0,
    "Operating Profit (Local)": 115.0,
    "Operating Margin (%)": 7.81,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 1472.0,
    "Operating Profit (EUR)": 115.0,
    "Work-for-Hire (EUR)": 780.16,
    "Owned IP (EUR)": 294.4,
    "Catalog & Format (EUR)": 397.44,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2018,
    "Company": "Fremantle",
    "Currency": "EUR",
    "Total Revenue (Local)": 1592.0,
    "Operating Profit (Local)": 147.0,
    "Operating Margin (%)": 9.23,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 1592.0,
    "Operating Profit (EUR)": 147.0,
    "Work-for-Hire (EUR)": 780.08,
    "Owned IP (EUR)": 382.08,
    "Catalog & Format (EUR)": 429.84,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2019,
    "Company": "Fremantle",
    "Currency": "EUR",
    "Total Revenue (Local)": 1793.0,
    "Operating Profit (Local)": 136.0,
    "Operating Margin (%)": 7.59,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 1793.0,
    "Operating Profit (EUR)": 136.0,
    "Work-for-Hire (EUR)": 824.78,
    "Owned IP (EUR)": 466.18,
    "Catalog & Format (EUR)": 502.04,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2020,
    "Company": "Fremantle",
    "Currency": "EUR",
    "Total Revenue (Local)": 1497.0,
    "Operating Profit (Local)": 115.0,
    "Operating Margin (%)": 7.68,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 1497.0,
    "Operating Profit (EUR)": 115.0,
    "Work-for-Hire (EUR)": 658.68,
    "Owned IP (EUR)": 419.16,
    "Catalog & Format (EUR)": 419.16,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2021,
    "Company": "Fremantle",
    "Currency": "EUR",
    "Total Revenue (Local)": 2182.0,
    "Operating Profit (Local)": 142.0,
    "Operating Margin (%)": 6.51,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 2182.0,
    "Operating Profit (EUR)": 142.0,
    "Work-for-Hire (EUR)": 850.98,
    "Owned IP (EUR)": 720.06,
    "Catalog & Format (EUR)": 610.96,
    "M&A Remark": "北欧の制作会社『This is Nice Group』から12の制作レーベルを買収し、北欧地域でのプレゼンスを拡大。",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2022,
    "Company": "Fremantle",
    "Currency": "EUR",
    "Total Revenue (Local)": 2347.0,
    "Operating Profit (Local)": 162.0,
    "Operating Margin (%)": 6.9,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 2347.0,
    "Operating Profit (EUR)": 162.0,
    "Work-for-Hire (EUR)": 844.92,
    "Owned IP (EUR)": 821.45,
    "Catalog & Format (EUR)": 680.63,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2023,
    "Company": "Fremantle",
    "Currency": "EUR",
    "Total Revenue (Local)": 2266.0,
    "Operating Profit (Local)": 139.0,
    "Operating Margin (%)": 6.13,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 2266.0,
    "Operating Profit (EUR)": 139.0,
    "Work-for-Hire (EUR)": 929.06,
    "Owned IP (EUR)": 679.8,
    "Catalog & Format (EUR)": 657.14,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2024,
    "Company": "Fremantle",
    "Currency": "EUR",
    "Total Revenue (Local)": 2254.0,
    "Operating Profit (Local)": 171.0,
    "Operating Margin (%)": 7.59,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 2254.0,
    "Operating Profit (EUR)": 171.0,
    "Work-for-Hire (EUR)": 1127.0,
    "Owned IP (EUR)": 450.8,
    "Catalog & Format (EUR)": 676.2,
    "M&A Remark": "Asacha Media Group（仏伊英のレーベルを保有）およびシンガポールのBeach House Picturesの買収を完了。",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2025,
    "Company": "Fremantle",
    "Currency": "EUR",
    "Total Revenue (Local)": 2043.0,
    "Operating Profit (Local)": 110.0,
    "Operating Margin (%)": 5.38,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 2043.0,
    "Operating Profit (EUR)": 110.0,
    "Work-for-Hire (EUR)": 1144.08,
    "Owned IP (EUR)": 245.16,
    "Catalog & Format (EUR)": 653.76,
    "M&A Remark": "RTLコンテンツ事業見直し：Fremantleは映画の全額出資（自己リスク）から撤退し、ドラマ前払金の評価減によりEBITA急落。",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2015,
    "Company": "BBC Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1327.0,
    "Operating Profit (Local)": 130.0,
    "Operating Margin (%)": 9.8,
    "Exchange Rate (to EUR)": 1.378,
    "Total Revenue (EUR)": 1828.61,
    "Operating Profit (EUR)": 179.14,
    "Work-for-Hire (EUR)": 914.3,
    "Owned IP (EUR)": 274.29,
    "Catalog & Format (EUR)": 640.01,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Estimate (Pre-Merger)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2016,
    "Company": "BBC Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1070.0,
    "Operating Profit (Local)": 140.0,
    "Operating Margin (%)": 13.08,
    "Exchange Rate (to EUR)": 1.2248,
    "Total Revenue (EUR)": 1310.54,
    "Operating Profit (EUR)": 171.47,
    "Work-for-Hire (EUR)": 629.06,
    "Owned IP (EUR)": 209.69,
    "Catalog & Format (EUR)": 471.79,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Estimate (Pre-Merger)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2017,
    "Company": "BBC Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1200.0,
    "Operating Profit (Local)": 150.0,
    "Operating Margin (%)": 12.5,
    "Exchange Rate (to EUR)": 1.1413,
    "Total Revenue (EUR)": 1369.56,
    "Operating Profit (EUR)": 171.19,
    "Work-for-Hire (EUR)": 630.0,
    "Owned IP (EUR)": 232.83,
    "Catalog & Format (EUR)": 506.74,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Estimate (Pre-Merger)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2018,
    "Company": "BBC Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1260.0,
    "Operating Profit (Local)": 159.0,
    "Operating Margin (%)": 12.62,
    "Exchange Rate (to EUR)": 1.1301,
    "Total Revenue (EUR)": 1423.93,
    "Operating Profit (EUR)": 179.69,
    "Work-for-Hire (EUR)": 626.53,
    "Owned IP (EUR)": 256.31,
    "Catalog & Format (EUR)": 541.09,
    "M&A Remark": "BBC Worldwide（商業販売）と旧BBC Studios（制作）が合併統合。制作と商業ライセンス活動を一本化。",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2019,
    "Company": "BBC Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1270.0,
    "Operating Profit (Local)": 181.0,
    "Operating Margin (%)": 14.25,
    "Exchange Rate (to EUR)": 1.1397,
    "Total Revenue (EUR)": 1447.42,
    "Operating Profit (EUR)": 206.29,
    "Work-for-Hire (EUR)": 593.44,
    "Owned IP (EUR)": 289.48,
    "Catalog & Format (EUR)": 564.49,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2020,
    "Company": "BBC Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1480.0,
    "Operating Profit (Local)": 151.0,
    "Operating Margin (%)": 10.2,
    "Exchange Rate (to EUR)": 1.1246,
    "Total Revenue (EUR)": 1664.41,
    "Operating Profit (EUR)": 169.81,
    "Work-for-Hire (EUR)": 682.41,
    "Owned IP (EUR)": 299.59,
    "Catalog & Format (EUR)": 682.41,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2021,
    "Company": "BBC Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1314.0,
    "Operating Profit (Local)": 226.0,
    "Operating Margin (%)": 17.2,
    "Exchange Rate (to EUR)": 1.163,
    "Total Revenue (EUR)": 1528.18,
    "Operating Profit (EUR)": 262.84,
    "Work-for-Hire (EUR)": 611.27,
    "Owned IP (EUR)": 259.79,
    "Catalog & Format (EUR)": 657.12,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2022,
    "Company": "BBC Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1530.0,
    "Operating Profit (Local)": 252.0,
    "Operating Margin (%)": 16.47,
    "Exchange Rate (to EUR)": 1.1733,
    "Total Revenue (EUR)": 1795.15,
    "Operating Profit (EUR)": 295.67,
    "Work-for-Hire (EUR)": 700.11,
    "Owned IP (EUR)": 287.22,
    "Catalog & Format (EUR)": 807.82,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2023,
    "Company": "BBC Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 2100.0,
    "Operating Profit (Local)": 240.0,
    "Operating Margin (%)": 11.43,
    "Exchange Rate (to EUR)": 1.1492,
    "Total Revenue (EUR)": 2413.32,
    "Operating Profit (EUR)": 275.81,
    "Work-for-Hire (EUR)": 917.06,
    "Owned IP (EUR)": 362.0,
    "Catalog & Format (EUR)": 1134.26,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2024,
    "Company": "BBC Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 1900.0,
    "Operating Profit (Local)": 202.0,
    "Operating Margin (%)": 10.63,
    "Exchange Rate (to EUR)": 1.1809,
    "Total Revenue (EUR)": 2243.71,
    "Operating Profit (EUR)": 238.54,
    "Work-for-Hire (EUR)": 830.17,
    "Owned IP (EUR)": 314.12,
    "Catalog & Format (EUR)": 1099.42,
    "M&A Remark": "ITVが保有する50%株式を2億5500万ポンドで買収し、配信サービス『BritBox International』を完全子会社化。",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2025,
    "Company": "BBC Studios",
    "Currency": "GBP",
    "Total Revenue (Local)": 2200.0,
    "Operating Profit (Local)": 225.0,
    "Operating Margin (%)": 10.23,
    "Exchange Rate (to EUR)": 1.1669,
    "Total Revenue (EUR)": 2567.18,
    "Operating Profit (EUR)": 262.55,
    "Work-for-Hire (EUR)": 924.18,
    "Owned IP (EUR)": 308.06,
    "Catalog & Format (EUR)": 1334.93,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2015,
    "Company": "Banijay Group",
    "Currency": "EUR",
    "Total Revenue (Local)": 360.0,
    "Operating Profit (Local)": 52.0,
    "Operating Margin (%)": 14.44,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 360.0,
    "Operating Profit (EUR)": 52.0,
    "Work-for-Hire (EUR)": 237.6,
    "Owned IP (EUR)": 43.2,
    "Catalog & Format (EUR)": 79.2,
    "M&A Remark": "Endemol Shine買収前の期間。欧州国内のローカルな制作スタジオ規模。",
    "Data Status (Revenue/Profit)": "Estimate (Pre-Endemol)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2016,
    "Company": "Banijay Group",
    "Currency": "EUR",
    "Total Revenue (Local)": 385.0,
    "Operating Profit (Local)": 58.0,
    "Operating Margin (%)": 15.06,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 385.0,
    "Operating Profit (EUR)": 58.0,
    "Work-for-Hire (EUR)": 246.4,
    "Owned IP (EUR)": 50.05,
    "Catalog & Format (EUR)": 88.55,
    "M&A Remark": "Endemol Shine買収前の期間。欧州国内のローカルな制作スタジオ規模。",
    "Data Status (Revenue/Profit)": "Estimate (Pre-Endemol)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2017,
    "Company": "Banijay Group",
    "Currency": "EUR",
    "Total Revenue (Local)": 410.0,
    "Operating Profit (Local)": 62.0,
    "Operating Margin (%)": 15.12,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 410.0,
    "Operating Profit (EUR)": 62.0,
    "Work-for-Hire (EUR)": 254.2,
    "Owned IP (EUR)": 57.4,
    "Catalog & Format (EUR)": 98.4,
    "M&A Remark": "Endemol Shine買収前の期間。欧州国内のローカルな制作スタジオ規模。",
    "Data Status (Revenue/Profit)": "Estimate (Pre-Endemol)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2018,
    "Company": "Banijay Group",
    "Currency": "EUR",
    "Total Revenue (Local)": 425.0,
    "Operating Profit (Local)": 65.0,
    "Operating Margin (%)": 15.29,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 425.0,
    "Operating Profit (EUR)": 65.0,
    "Work-for-Hire (EUR)": 259.25,
    "Owned IP (EUR)": 63.75,
    "Catalog & Format (EUR)": 102.0,
    "M&A Remark": "Endemol Shine買収前の期間。欧州国内のローカルな制作スタジオ規模。",
    "Data Status (Revenue/Profit)": "Estimate (Pre-Endemol)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2019,
    "Company": "Banijay Group",
    "Currency": "EUR",
    "Total Revenue (Local)": 430.0,
    "Operating Profit (Local)": 68.0,
    "Operating Margin (%)": 15.81,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 430.0,
    "Operating Profit (EUR)": 68.0,
    "Work-for-Hire (EUR)": 253.7,
    "Owned IP (EUR)": 68.8,
    "Catalog & Format (EUR)": 107.5,
    "M&A Remark": "Endemol Shine買収前の期間。欧州国内のローカルな制作スタジオ規模。",
    "Data Status (Revenue/Profit)": "Estimate (Pre-Endemol)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2020,
    "Company": "Banijay Group",
    "Currency": "EUR",
    "Total Revenue (Local)": 1620.0,
    "Operating Profit (Local)": 240.0,
    "Operating Margin (%)": 14.81,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 1620.0,
    "Operating Profit (EUR)": 240.0,
    "Work-for-Hire (EUR)": 615.6,
    "Owned IP (EUR)": 356.4,
    "Catalog & Format (EUR)": 648.0,
    "M&A Remark": "22億ユーロでのEndemol Shine Groupの買収を完了。売上が倍増し、『Big Brother』等の世界的フォーマットを獲得。",
    "Data Status (Revenue/Profit)": "Pro-forma Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2021,
    "Company": "Banijay Group",
    "Currency": "EUR",
    "Total Revenue (Local)": 2750.0,
    "Operating Profit (Local)": 435.0,
    "Operating Margin (%)": 15.82,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 2750.0,
    "Operating Profit (EUR)": 435.0,
    "Work-for-Hire (EUR)": 962.5,
    "Owned IP (EUR)": 660.0,
    "Catalog & Format (EUR)": 1127.5,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2022,
    "Company": "Banijay Group",
    "Currency": "EUR",
    "Total Revenue (Local)": 3210.0,
    "Operating Profit (Local)": 510.0,
    "Operating Margin (%)": 15.89,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 3210.0,
    "Operating Profit (EUR)": 510.0,
    "Work-for-Hire (EUR)": 1059.3,
    "Owned IP (EUR)": 802.5,
    "Catalog & Format (EUR)": 1348.2,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2023,
    "Company": "Banijay Group",
    "Currency": "EUR",
    "Total Revenue (Local)": 4318.0,
    "Operating Profit (Local)": 737.0,
    "Operating Margin (%)": 17.07,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 4318.0,
    "Operating Profit (EUR)": 737.0,
    "Work-for-Hire (EUR)": 1468.12,
    "Owned IP (EUR)": 949.96,
    "Catalog & Format (EUR)": 1899.92,
    "M&A Remark": "Balich Wonder Studioの買収を完了。ライブ体験や大型イベント・セレモニーの制作セグメントを新たに追加。",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2024,
    "Company": "Banijay Group",
    "Currency": "EUR",
    "Total Revenue (Local)": 4803.0,
    "Operating Profit (Local)": 900.0,
    "Operating Margin (%)": 18.74,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 4803.0,
    "Operating Profit (EUR)": 900.0,
    "Work-for-Hire (EUR)": 1681.05,
    "Owned IP (EUR)": 912.57,
    "Catalog & Format (EUR)": 2209.38,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2025,
    "Company": "Banijay Group",
    "Currency": "EUR",
    "Total Revenue (Local)": 4881.0,
    "Operating Profit (Local)": 961.0,
    "Operating Margin (%)": 19.69,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 4881.0,
    "Operating Profit (EUR)": 961.0,
    "Work-for-Hire (EUR)": 1757.16,
    "Owned IP (EUR)": 780.96,
    "Catalog & Format (EUR)": 2342.88,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2015,
    "Company": "Mediawan",
    "Currency": "EUR",
    "Total Revenue (Local)": 10.0,
    "Operating Profit (Local)": 1.2,
    "Operating Margin (%)": 12.0,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 10.0,
    "Operating Profit (EUR)": 1.2,
    "Work-for-Hire (EUR)": 7.5,
    "Owned IP (EUR)": 1.0,
    "Catalog & Format (EUR)": 1.5,
    "M&A Remark": "SPAC（特別買収目的会社）段階。フランス国内のインディペンデントレーベル（AB Groupe等）の初期統合期。",
    "Data Status (Revenue/Profit)": "Actual (SPAC)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2016,
    "Company": "Mediawan",
    "Currency": "EUR",
    "Total Revenue (Local)": 15.0,
    "Operating Profit (Local)": 1.8,
    "Operating Margin (%)": 12.0,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 15.0,
    "Operating Profit (EUR)": 1.8,
    "Work-for-Hire (EUR)": 11.1,
    "Owned IP (EUR)": 1.5,
    "Catalog & Format (EUR)": 2.4,
    "M&A Remark": "SPAC（特別買収目的会社）段階。フランス国内のインディペンデントレーベル（AB Groupe等）の初期統合期。",
    "Data Status (Revenue/Profit)": "Actual (SPAC)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2017,
    "Company": "Mediawan",
    "Currency": "EUR",
    "Total Revenue (Local)": 180.0,
    "Operating Profit (Local)": 18.0,
    "Operating Margin (%)": 10.0,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 180.0,
    "Operating Profit (EUR)": 18.0,
    "Work-for-Hire (EUR)": 126.0,
    "Owned IP (EUR)": 21.6,
    "Catalog & Format (EUR)": 32.4,
    "M&A Remark": "SPAC（特別買収目的会社）段階。フランス国内のインディペンデントレーベル（AB Groupe等）の初期統合期。",
    "Data Status (Revenue/Profit)": "Actual (SPAC)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2018,
    "Company": "Mediawan",
    "Currency": "EUR",
    "Total Revenue (Local)": 240.0,
    "Operating Profit (Local)": 25.0,
    "Operating Margin (%)": 10.42,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 240.0,
    "Operating Profit (EUR)": 25.0,
    "Work-for-Hire (EUR)": 160.8,
    "Owned IP (EUR)": 33.6,
    "Catalog & Format (EUR)": 45.6,
    "M&A Remark": "SPAC（特別買収目的会社）段階。フランス国内のインディペンデントレーベル（AB Groupe等）の初期統合期。",
    "Data Status (Revenue/Profit)": "Actual (SPAC)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2019,
    "Company": "Mediawan",
    "Currency": "EUR",
    "Total Revenue (Local)": 260.0,
    "Operating Profit (Local)": 27.0,
    "Operating Margin (%)": 10.38,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 260.0,
    "Operating Profit (EUR)": 27.0,
    "Work-for-Hire (EUR)": 169.0,
    "Owned IP (EUR)": 39.0,
    "Catalog & Format (EUR)": 52.0,
    "M&A Remark": "SPAC（特別買収目的会社）段階。フランス国内のインディペンデントレーベル（AB Groupe等）の初期統合期。",
    "Data Status (Revenue/Profit)": "Actual (SPAC)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2020,
    "Company": "Mediawan",
    "Currency": "EUR",
    "Total Revenue (Local)": 350.0,
    "Operating Profit (Local)": 32.0,
    "Operating Margin (%)": 9.14,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 350.0,
    "Operating Profit (EUR)": 32.0,
    "Work-for-Hire (EUR)": 185.5,
    "Owned IP (EUR)": 87.5,
    "Catalog & Format (EUR)": 77.0,
    "M&A Remark": "KKR主導による非公開化が完了。ドイツのLeonine Studiosとの戦略的アライアンス・提携を開始。",
    "Data Status (Revenue/Profit)": "Estimate (Private)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2021,
    "Company": "Mediawan",
    "Currency": "EUR",
    "Total Revenue (Local)": 520.0,
    "Operating Profit (Local)": 45.0,
    "Operating Margin (%)": 8.65,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 520.0,
    "Operating Profit (EUR)": 45.0,
    "Work-for-Hire (EUR)": 254.8,
    "Owned IP (EUR)": 145.6,
    "Catalog & Format (EUR)": 119.6,
    "M&A Remark": "KKR主導による非公開化が完了。ドイツのLeonine Studiosとの戦略的アライアンス・提携を開始。",
    "Data Status (Revenue/Profit)": "Estimate (Private)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2022,
    "Company": "Mediawan",
    "Currency": "EUR",
    "Total Revenue (Local)": 710.0,
    "Operating Profit (Local)": 62.0,
    "Operating Margin (%)": 8.73,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 710.0,
    "Operating Profit (EUR)": 62.0,
    "Work-for-Hire (EUR)": 312.4,
    "Owned IP (EUR)": 227.2,
    "Catalog & Format (EUR)": 170.4,
    "M&A Remark": "KKR主導による非公開化が完了。ドイツのLeonine Studiosとの戦略的アライアンス・提携を開始。",
    "Data Status (Revenue/Profit)": "Estimate (Private)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2023,
    "Company": "Mediawan",
    "Currency": "EUR",
    "Total Revenue (Local)": 950.0,
    "Operating Profit (Local)": 85.0,
    "Operating Margin (%)": 8.95,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 950.0,
    "Operating Profit (EUR)": 85.0,
    "Work-for-Hire (EUR)": 380.0,
    "Owned IP (EUR)": 332.5,
    "Catalog & Format (EUR)": 237.5,
    "M&A Remark": "KKR主導による非公開化が完了。ドイツのLeonine Studiosとの戦略的アライアンス・提携を開始。",
    "Data Status (Revenue/Profit)": "Estimate (Private)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2024,
    "Company": "Mediawan",
    "Currency": "EUR",
    "Total Revenue (Local)": 1068.0,
    "Operating Profit (Local)": 13.6,
    "Operating Margin (%)": 1.27,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 1068.0,
    "Operating Profit (EUR)": 13.6,
    "Work-for-Hire (EUR)": 341.76,
    "Owned IP (EUR)": 320.4,
    "Catalog & Format (EUR)": 405.84,
    "M&A Remark": "独Leonine Studiosの完全子会社化および米The North Road Company（NRC）への出資を完了。欧米をカバーする巨大IPスタジオへ変容。",
    "Data Status (Revenue/Profit)": "Estimate (Private)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2025,
    "Company": "Mediawan",
    "Currency": "EUR",
    "Total Revenue (Local)": 1150.0,
    "Operating Profit (Local)": 95.0,
    "Operating Margin (%)": 8.26,
    "Exchange Rate (to EUR)": 1.0,
    "Total Revenue (EUR)": 1150.0,
    "Operating Profit (EUR)": 95.0,
    "Work-for-Hire (EUR)": 414.0,
    "Owned IP (EUR)": 276.0,
    "Catalog & Format (EUR)": 460.0,
    "M&A Remark": "独Leonine Studiosの完全子会社化および米The North Road Company（NRC）への出資を完了。欧米をカバーする巨大IPスタジオへ変容。",
    "Data Status (Revenue/Profit)": "Estimate (Est)",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2015,
    "Company": "All3Media",
    "Currency": "GBP",
    "Total Revenue (Local)": 705.0,
    "Operating Profit (Local)": 75.0,
    "Operating Margin (%)": 10.64,
    "Exchange Rate (to EUR)": 1.378,
    "Total Revenue (EUR)": 971.49,
    "Operating Profit (EUR)": 103.35,
    "Work-for-Hire (EUR)": 582.89,
    "Owned IP (EUR)": 116.58,
    "Catalog & Format (EUR)": 272.02,
    "M&A Remark": "Liberty GlobalとDiscovery（現WBD）の共同所有体制となって最初のフル会計年度。",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2016,
    "Company": "All3Media",
    "Currency": "GBP",
    "Total Revenue (Local)": 810.0,
    "Operating Profit (Local)": 82.0,
    "Operating Margin (%)": 10.12,
    "Exchange Rate (to EUR)": 1.2248,
    "Total Revenue (EUR)": 992.09,
    "Operating Profit (EUR)": 100.43,
    "Work-for-Hire (EUR)": 575.41,
    "Owned IP (EUR)": 128.97,
    "Catalog & Format (EUR)": 287.71,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2017,
    "Company": "All3Media",
    "Currency": "GBP",
    "Total Revenue (Local)": 847.0,
    "Operating Profit (Local)": 85.0,
    "Operating Margin (%)": 10.04,
    "Exchange Rate (to EUR)": 1.1413,
    "Total Revenue (EUR)": 966.68,
    "Operating Profit (EUR)": 97.01,
    "Work-for-Hire (EUR)": 551.01,
    "Owned IP (EUR)": 145.0,
    "Catalog & Format (EUR)": 270.67,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2018,
    "Company": "All3Media",
    "Currency": "GBP",
    "Total Revenue (Local)": 890.0,
    "Operating Profit (Local)": 90.0,
    "Operating Margin (%)": 10.11,
    "Exchange Rate (to EUR)": 1.1301,
    "Total Revenue (EUR)": 1005.79,
    "Operating Profit (EUR)": 101.71,
    "Work-for-Hire (EUR)": 543.13,
    "Owned IP (EUR)": 170.98,
    "Catalog & Format (EUR)": 291.68,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2019,
    "Company": "All3Media",
    "Currency": "GBP",
    "Total Revenue (Local)": 930.0,
    "Operating Profit (Local)": 95.0,
    "Operating Margin (%)": 10.22,
    "Exchange Rate (to EUR)": 1.1397,
    "Total Revenue (EUR)": 1059.92,
    "Operating Profit (EUR)": 108.27,
    "Work-for-Hire (EUR)": 551.16,
    "Owned IP (EUR)": 190.79,
    "Catalog & Format (EUR)": 317.98,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2020,
    "Company": "All3Media",
    "Currency": "GBP",
    "Total Revenue (Local)": 780.0,
    "Operating Profit (Local)": 60.0,
    "Operating Margin (%)": 7.69,
    "Exchange Rate (to EUR)": 1.1246,
    "Total Revenue (EUR)": 877.19,
    "Operating Profit (EUR)": 67.48,
    "Work-for-Hire (EUR)": 456.14,
    "Owned IP (EUR)": 140.35,
    "Catalog & Format (EUR)": 280.7,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2021,
    "Company": "All3Media",
    "Currency": "GBP",
    "Total Revenue (Local)": 866.0,
    "Operating Profit (Local)": 72.0,
    "Operating Margin (%)": 8.31,
    "Exchange Rate (to EUR)": 1.163,
    "Total Revenue (EUR)": 1007.16,
    "Operating Profit (EUR)": 83.74,
    "Work-for-Hire (EUR)": 503.58,
    "Owned IP (EUR)": 191.36,
    "Catalog & Format (EUR)": 312.22,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2022,
    "Company": "All3Media",
    "Currency": "GBP",
    "Total Revenue (Local)": 940.0,
    "Operating Profit (Local)": 88.0,
    "Operating Margin (%)": 9.36,
    "Exchange Rate (to EUR)": 1.1733,
    "Total Revenue (EUR)": 1102.9,
    "Operating Profit (EUR)": 103.25,
    "Work-for-Hire (EUR)": 529.39,
    "Owned IP (EUR)": 242.64,
    "Catalog & Format (EUR)": 330.87,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2023,
    "Company": "All3Media",
    "Currency": "GBP",
    "Total Revenue (Local)": 995.1,
    "Operating Profit (Local)": 107.4,
    "Operating Margin (%)": 10.79,
    "Exchange Rate (to EUR)": 1.1492,
    "Total Revenue (EUR)": 1143.57,
    "Operating Profit (EUR)": 123.42,
    "Work-for-Hire (EUR)": 537.48,
    "Owned IP (EUR)": 205.84,
    "Catalog & Format (EUR)": 400.24,
    "M&A Remark": "世界的ヒット番組『The Traitors（ザ・トレイターズ）』の20カ国以上への展開・ライセンスによる好調な売上。",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2024,
    "Company": "All3Media",
    "Currency": "GBP",
    "Total Revenue (Local)": 895.9,
    "Operating Profit (Local)": 105.3,
    "Operating Margin (%)": 11.75,
    "Exchange Rate (to EUR)": 1.1809,
    "Total Revenue (EUR)": 1057.97,
    "Operating Profit (EUR)": 124.35,
    "Work-for-Hire (EUR)": 507.82,
    "Owned IP (EUR)": 158.69,
    "Catalog & Format (EUR)": 391.44,
    "M&A Remark": "RedBird IMIが、LibertyおよびWBDから11億5000万ポンドでAll3Mediaの買収を完了。",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  },
  {
    "Year": 2025,
    "Company": "All3Media",
    "Currency": "GBP",
    "Total Revenue (Local)": 980.0,
    "Operating Profit (Local)": 95.0,
    "Operating Margin (%)": 9.69,
    "Exchange Rate (to EUR)": 1.1669,
    "Total Revenue (EUR)": 1143.56,
    "Operating Profit (EUR)": 110.86,
    "Work-for-Hire (EUR)": 548.91,
    "Owned IP (EUR)": 160.1,
    "Catalog & Format (EUR)": 434.55,
    "M&A Remark": "",
    "Data Status (Revenue/Profit)": "Actual",
    "Axis A Valuation Method": "Scenario-based Allocation (想定値)"
  }
];